### ISSUE TITLE
[Question] Does this show everyone's Optifine Capes?

### ISSUE THREAD

**Issue by TheCodingCarson** [Neylux/OptifineCapes#1]
**-- Question - not an issue --**

If another user in the Minecraft server I'm in has an Optifine donator cape also will I be able to see there cap?

**Comment by Neylux** [comment]
Yes you **SHOULD** also see their optifine cape. If this is not the case feel free to report it, but that is the intended behaviour.

**Comment by TheCodingCarson** [comment]
Thank you, was the only thing I was missing after switching to Neoforge!

Any chance you can release it on Modrinth? Would be great for the Modrinth app plus easy to follow updates as they come.

**Comment by Neylux** [comment]
No problem just submitted the mod to modrinth for REVIEW. It will probably take some time for it to show up, but it should be available under the link below when it is published:
https://modrinth.com/mod/showmyoptifinecape
